# Generated by Django 3.2.9 on 2021-11-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='campos',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
