# Generated by Django 3.2.9 on 2021-11-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_campos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='campos',
        ),
    ]
