# Generated by Django 3.2.9 on 2021-11-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('complemento', models.CharField(max_length=200, null=True)),
                ('bairro', models.CharField(max_length=50, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('pais', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=1)),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=15, unique=True)),
                ('Endereco', models.OneToOneField(default='P', on_delete=django.db.models.deletion.CASCADE, to='aplicacao.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=1)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('Endereco', models.OneToOneField(default='P', on_delete=django.db.models.deletion.CASCADE, to='aplicacao.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
