# Generated by Django 2.2.12 on 2021-11-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='TIPO_CHOICES',
            field=models.CharField(choices=[('C', 'Comercial'), ('F', 'Fixo'), ('P', 'Pessoal')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='TIPO_CHOICES',
            field=models.CharField(choices=[('C', 'Comercial'), ('F', 'Fixo'), ('P', 'Pessoal')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
