# Generated by Django 3.2.9 on 2021-11-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_pessoafisica_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='Endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='Endereco',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aplicacao.endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aplicacao.endereco'),
            preserve_default=False,
        ),
    ]
