# Generated by Django 3.2.9 on 2021-11-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_auto_20211110_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='aplicacao.endereco'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='aplicacao.endereco'),
        ),
    ]
