# Generated by Django 3.2.9 on 2021-11-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_auto_20211111_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='nome_fantasia',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='bairro',
            field=models.CharField(max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cidade',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='complemento',
            field=models.CharField(max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='estado',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='rua',
            field=models.CharField(max_length=200, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='bairro',
            field=models.CharField(max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cidade',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='complemento',
            field=models.CharField(max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='estado',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='rua',
            field=models.CharField(max_length=200, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='tipo',
            field=models.CharField(choices=[('C', 'Comercial'), ('F', 'Fixo'), ('P', 'Pessoal')], default='P', max_length=1, verbose_name='Tipo de telefone'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=15, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='tipo',
            field=models.CharField(choices=[('C', 'Comercial'), ('F', 'Fixo'), ('P', 'Pessoal')], default='P', max_length=1, verbose_name='Tipo de telefone'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
