# Generated by Django 3.2.9 on 2021-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_auto_20211111_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='sobre',
            field=models.CharField(default=1, max_length=200, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
