# Generated by Django 3.2.7 on 2021-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_auto_20211111_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='rua',
            field=models.CharField(max_length=200, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='rua',
            field=models.CharField(max_length=200, null=True, verbose_name='Rua'),
        ),
    ]
